export const jobs = [
  {
    id: "1",
    title: "Forward Security Director",
    company: "Reach, Fortitude and Strategi Inc.",
    location: "New York, USA",
    type: "Full-time",
    category: "Technology",
    salary: "$120,000-$140,000",
    description:
      "We are looking for a Forward Security Director to lead our security initiatives and ensure the protection of our digital assets.",
    requirements: [
      "7+ years of experience in cybersecurity",
      "Strong knowledge of security frameworks and best practices",
      "Experience with cloud security and infrastructure protection",
      "Leadership skills and ability to manage a team",
      "Relevant certifications (CISSP, CISM, etc.)",
    ],
    benefits: [
      "Competitive salary",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Flexible work arrangements",
      "Professional development opportunities",
    ],
    contactEmail: "careers@reachfortitude.com",
    applicationUrl: "https://careers.reachfortitude.com/jobs/security-director",
    companyLogo: "/placeholder.svg?height=40&width=40",
    postedDate: "2023-05-10T10:30:00Z",
    postedDays: 2,
    featured: true,
  },
  {
    id: "2",
    title: "Regional Creative Facilitator",
    company: "Sketch - Studio Inc.",
    location: "Los Angeles, USA",
    type: "Full-time",
    category: "Design",
    salary: "$90,000-$110,000",
    description:
      "Join our creative team as a Regional Creative Facilitator to help drive innovation and design excellence across our regional projects.",
    requirements: [
      "5+ years of experience in creative direction or design management",
      "Strong portfolio demonstrating creative excellence",
      "Experience facilitating creative workshops and team collaboration",
      "Excellent communication and presentation skills",
      "Bachelor's degree in Design, Fine Arts, or related field",
    ],
    benefits: [
      "Competitive salary",
      "Health benefits",
      "Creative workspace",
      "Flexible hours",
      "Professional development budget",
    ],
    contactEmail: "jobs@sketchstudio.com",
    applicationUrl: "https://sketchstudio.com/careers",
    companyLogo: "/placeholder.svg?height=40&width=40",
    postedDate: "2023-05-09T14:20:00Z",
    postedDays: 3,
    featured: true,
  },
  {
    id: "3",
    title: "Internal Integration Planner",
    company: "Trello, Spotify and Figma Inc.",
    location: "Texas, USA",
    type: "Full-time",
    category: "Technology",
    salary: "$100,000-$120,000",
    description:
      "We're seeking an Internal Integration Planner to help streamline our internal systems and improve cross-platform functionality.",
    requirements: [
      "Experience with API integrations and system architecture",
      "Strong knowledge of SaaS platforms and integration patterns",
      "Project management skills",
      "Technical background with understanding of software development",
      "Excellent problem-solving abilities",
    ],
    benefits: [
      "Competitive compensation",
      "Comprehensive benefits package",
      "Remote work options",
      "Learning and development opportunities",
      "Employee stock purchase plan",
    ],
    contactEmail: "careers@trellospotify.com",
    applicationUrl: "https://careers.trellospotify.com/jobs",
    companyLogo: "/placeholder.svg?height=40&width=40",
    postedDate: "2023-05-07T09:15:00Z",
    postedDays: 5,
    featured: false,
  },
  {
    id: "4",
    title: "District Intranet Director",
    company: "VoiceRadar - Media Inc.",
    location: "Nevada, USA",
    type: "Full-time",
    category: "Technology",
    salary: "$110,000-$130,000",
    description:
      "Lead the development and management of our district-wide intranet system to improve internal communications and information sharing.",
    requirements: [
      "Experience managing intranet platforms",
      "Knowledge of content management systems",
      "Understanding of UX/UI principles",
      "Strong leadership and communication skills",
      "Technical background in web technologies",
    ],
    benefits: [
      "Competitive salary",
      "Comprehensive benefits",
      "Flexible work arrangements",
      "Professional development opportunities",
      "Collaborative work environment",
    ],
    contactEmail: "hr@voiceradar.com",
    applicationUrl: "https://careers.voiceradar.com",
    companyLogo: "/placeholder.svg?height=40&width=40",
    postedDate: "2023-05-05T11:30:00Z",
    postedDays: 7,
    featured: false,
  },
  {
    id: "5",
    title: "Corporate Tactics Facilitator",
    company: "Central, Focal and Metrics Inc.",
    location: "Boston, USA",
    type: "Full-time",
    category: "Business",
    salary: "$95,000-$115,000",
    description:
      "Join our strategic team to develop and implement corporate tactics that drive business growth and operational excellence.",
    requirements: [
      "Experience in corporate strategy or management consulting",
      "Strong analytical and problem-solving skills",
      "Excellent facilitation and presentation abilities",
      "Business or related degree",
      "Project management experience",
    ],
    benefits: [
      "Competitive compensation package",
      "Health and wellness benefits",
      "Retirement plan with company match",
      "Professional development opportunities",
      "Collaborative work environment",
    ],
    contactEmail: "careers@centralfocal.com",
    applicationUrl: "https://centralfocal.com/careers",
    companyLogo: "/placeholder.svg?height=40&width=40",
    postedDate: "2023-05-04T10:00:00Z",
    postedDays: 8,
    featured: false,
  },
  {
    id: "6",
    title: "Forward Accounts Consultant",
    company: "Plato, Inc.",
    location: "Boston, USA",
    type: "Full-time",
    category: "Finance",
    salary: "$85,000-$105,000",
    description:
      "We're looking for a Forward Accounts Consultant to provide expert financial guidance to our clients and help them achieve their financial goals.",
    requirements: [
      "CPA or relevant financial certification",
      "Experience in accounting or financial consulting",
      "Strong analytical and problem-solving skills",
      "Excellent communication abilities",
      "Knowledge of financial regulations and compliance",
    ],
    benefits: [
      "Competitive salary",
      "Comprehensive benefits package",
      "Professional development opportunities",
      "Work-life balance",
      "Collaborative team environment",
    ],
    contactEmail: "jobs@plato.com",
    applicationUrl: "https://plato.com/careers",
    companyLogo: "/placeholder.svg?height=40&width=40",
    postedDate: "2023-05-02T14:45:00Z",
    postedDays: 10,
    featured: false,
  },
]

export const categories = [
  { id: "technology", name: "Technology", count: 1250 },
  { id: "agriculture", name: "Agriculture", count: 1250 },
  { id: "metal-production", name: "Metal Production", count: 1450 },
  { id: "commerce", name: "Commerce", count: 1300 },
  { id: "construction", name: "Construction", count: 1500 },
  { id: "hotels-tourism", name: "Hotels & Tourism", count: 1350 },
  { id: "education", name: "Education", count: 1400 },
  { id: "financial-services", name: "Financial Services", count: 1550 },
  { id: "transport", name: "Transport", count: 1200 },
  { id: "healthcare", name: "Healthcare", count: 1350 },
  { id: "design", name: "Design", count: 980 },
  { id: "marketing", name: "Marketing", count: 1100 },
  { id: "business", name: "Business", count: 1250 },
  { id: "finance", name: "Finance", count: 1050 },
  { id: "sales", name: "Sales", count: 950 },
]

export const companies = [
  {
    id: "instagram",
    name: "Instagram",
    logo: "/placeholder.svg?height=60&width=60",
    description: "Find jobs from Instagram and explore career opportunities at this social media giant.",
    jobCount: 25,
    location: "Menlo Park, CA",
    website: "https://instagram.com/careers",
    industry: "Technology",
  },
  {
    id: "tesla",
    name: "Tesla",
    logo: "/placeholder.svg?height=60&width=60",
    description: "Join the electric revolution with Tesla and work on cutting-edge sustainable energy solutions.",
    jobCount: 32,
    location: "Palo Alto, CA",
    website: "https://tesla.com/careers",
    industry: "Automotive & Energy",
  },
  {
    id: "mcdonalds",
    name: "McDonald's",
    logo: "/placeholder.svg?height=60&width=60",
    description: "Explore diverse roles at McDonald's, from restaurant operations to corporate positions.",
    jobCount: 18,
    location: "Chicago, IL",
    website: "https://mcdonalds.com/careers",
    industry: "Food & Beverage",
  },
  {
    id: "apple",
    name: "Apple",
    logo: "/placeholder.svg?height=60&width=60",
    description: "Be part of Apple's innovative team and help create products that change the world.",
    jobCount: 40,
    location: "Cupertino, CA",
    website: "https://apple.com/careers",
    industry: "Technology",
  },
]
