name: SonarCloud analysis

on:
  push:
    branches: ['**']              # Run on all branches
  pull_request:
    branches: ['**']              # Run on all PRs targeting any branch
  workflow_dispatch:              # Allow manual trigger

permissions:
  pull-requests: read             # Needed for PR decoration

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=jpesewang_job-winner-fe
            -Dsonar.organization=jpesewang
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=_tests_/**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
